// <auto-generated />
namespace EmployeeManagement_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class EntityUpdateCheck : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityUpdateCheck));
        
        string IMigrationMetadata.Id
        {
            get { return "202502061454335_Entity-UpdateCheck"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
